export const Theme = {
  light: {
    theme: "light",
    color: "black",
    text: "black",
    bordercolor: "#474747",
    background: "white",
    cardbackground: "#ffffff",
    homepageBackground: "#F3F3F3",
    tabactive: "#0300AA",
    tabInactive: "black",
    popupContain: "grey",
    forgotPassBg: "lightgrey",
    coloring: "#0300AA",
    coloringViceVersa: "#FF6B00",
    fontLight: "#474747CC",
    dropdownBg: "white",
    footer: "#F1F1F1",
  },
  dark: {
    theme: "dark",
    color: "#BBBBBB",
    text: "grey",
    background: "#000000",
    homepageBackground: "#000000",
    cardbackground: "#f1f1f1",
    bordercolor: "#EEEEEE",
    tabactive: "orange",
    tabInactive: "white",
    popupContain: "black",
    forgotPassBg: "black",
    coloring: "#FF6B00",
    coloringViceVersa: "#0300AA",
    fontLight: "#f1f1f1",
    dropdownBg: "white",
    grey: "#EEEEEE",
    footer: "#222222",
  },
};
